//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCY
    {
        public int CODE { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> SERIAL_NUMBER { get; set; }
        public Nullable<int> REG_NUM { get; set; }
        public string ENTRUSTED_NAME_1 { get; set; }
        public string ENTRUSTED_NAME_2 { get; set; }
        public string ENTRUSTED_NAME_3 { get; set; }
        public string ENTRUSTED_NAME_4 { get; set; }
        public string ENTRUSTED_NAME_5 { get; set; }
        public string AGENT_NAME_1 { get; set; }
        public string AGENT_NAME_2 { get; set; }
        public string AGENT_NAME_3 { get; set; }
        public string AGENT_NAME_4 { get; set; }
        public string AGENT_NAME_5 { get; set; }
        public string SALES_MAN { get; set; }
        public Nullable<System.DateTime> AGENCY_DATE { get; set; }
        public byte[] IMAGE { get; set; }
        public string STAT { get; set; }
        public string EDITOR { get; set; }
        public string UESER_NAME { get; set; }
        public string TYPE_2 { get; set; }
        public string SECURITY_NO { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
    }
}
