//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_COMPANY
    {
        public int CODE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TYPE { get; set; }
        public string ENTRUSTED_NAME { get; set; }
        public string EDITOR { get; set; }
        public string SALES_MAN { get; set; }
        public string RECEIPT_NO_1 { get; set; }
        public string RECEIPT_NO_2 { get; set; }
        public string NOTES { get; set; }
        public string STAT { get; set; }
        public string UESER_NAME { get; set; }
    }
}
