//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEES
    {
        public string ADESC { get; set; }
        public string VAL_1 { get; set; }
        public string VAL_2 { get; set; }
        public string VAL_3 { get; set; }
        public string VAL_4 { get; set; }
        public string VAL_5 { get; set; }
        public string VAL_6 { get; set; }
        public string VAL_7 { get; set; }
        public string VAL_8 { get; set; }
        public string TOTAL { get; set; }
    }
}
