//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORGED_AGENCY
    {
        public int NO { get; set; }
        public string CODE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string AGENCY_CODE { get; set; }
        public Nullable<System.DateTime> DATE_TODAY { get; set; }
        public string USER_NAME { get; set; }
    }
}
