//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Syrian_Bar_DBEntities : DbContext
    {
        public Syrian_Bar_DBEntities()
            : base("name=Syrian_Bar_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENCY> AGENCY { get; set; }
        public virtual DbSet<BLOCK_AGENCY> BLOCK_AGENCY { get; set; }
        public virtual DbSet<CONTRACT_COMPANY> CONTRACT_COMPANY { get; set; }
        public virtual DbSet<DISMISSAL_AGENCY> DISMISSAL_AGENCY { get; set; }
        public virtual DbSet<FA_COMPANY> FA_COMPANY { get; set; }
        public virtual DbSet<FA_COMPANY2> FA_COMPANY2 { get; set; }
        public virtual DbSet<FEES> FEES { get; set; }
        public virtual DbSet<FORGED_AGENCY> FORGED_AGENCY { get; set; }
        public virtual DbSet<NUM_RECORD> NUM_RECORD { get; set; }
        public virtual DbSet<PRINT_LOG> PRINT_LOG { get; set; }
        public virtual DbSet<RETIREMENT_AGENCY> RETIREMENT_AGENCY { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
