//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_LOG
    {
        public int CODE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TYPE_PRINT { get; set; }
        public string CODE_AG { get; set; }
        public string DATE_AG { get; set; }
        public string SN_AG { get; set; }
        public string REG_AG { get; set; }
        public string NAME_AG { get; set; }
        public string TYPE_AG { get; set; }
        public string EDITOR_AG { get; set; }
        public string SALESMAN_AG { get; set; }
        public string NOTES { get; set; }
        public string WITHOUT_TAX { get; set; }
        public string VAL_1 { get; set; }
        public string VAL_2 { get; set; }
        public string VAL_3 { get; set; }
        public string VAL_4 { get; set; }
        public string VAL_5 { get; set; }
        public string VAL_6 { get; set; }
        public string VAL_7 { get; set; }
        public string VAL_8 { get; set; }
        public string VAL_9 { get; set; }
        public string ARCHIVE { get; set; }
        public string SECURITY_NO { get; set; }
    }
}
